[DATA]
dir = "**PATH_TO_DATADIR**"


[LEDGER]
snapshot_interval = 225 # 15m
snapshot_backfill_interval = 3600 # 4h
snapshot_in_memory = false
min_trustlines = 3
capture_whales = 100
top_percenters = [0.01, 0.1, 1.0, 10.0, 25.0, 50.0]



[XUMM]
api_key = "**REDACTED**"
api_secret = "**REDACTED**"
refresh_interval_assets = 600
refresh_interval_kyc = 86400
max_requests_per_minute = 60

[BITHOMP]
refresh_interval = 600
api_key = "**REDACTED**"

[XRPSCAN]
refresh_interval = 600

[TWITTER]
bearer_token = "**REDACTED**"
refresh_interval = 3600
max_requests_per_minute = 60

[GRAVATAR]
refresh_interval = 3600
max_requests_per_minute = 60



[[NODES]]
disabled = true
url = "wss://s1.ripple.com"
allowed_commands = ['subscribe']


[[NODES]]
url = "ws://xrptrader.org:4920"
connections = 3
allowed_commands = ['subscribe', 'ledger', 'ledger_data']