[DATA]
dir = "V:/xrpl/xrplmeta"

[CACHE]
in_memory = false

[SERVER]
port=4080

[META]
source_priorities = ['ledger', 'website', 'xumm', 'bithomp', 'xrpscan', 'twitter', 'gravatar']

[EXCHANGES]
candle_intervals = {15m = 900, 1H = 3600, 4H = 14400, 1D = 86400}
raw_limit = 1000