[DATA]
dir = "/Users/mwni/Documents/xrpl"

[CACHE]
in_memory = false

[SERVER]
port=4080

[META]
source_priorities = ['ledger', 'website', 'xumm.app', 'xumm.pro', 'bithomp.com', 'xrpscan.com', 'twitter.com', 'gravatar.com']

[EXCHANGES]
candle_intervals = {15m = 900, 1H = 3600, 4H = 14400, 1D = 86400}
raw_limit = 1000